apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
        grafana: "true"
        role: db
    spec:
      containers:
        - image: cedriclam/grafana-prometheus:latest
          imagePullPolicy: Always
          name: grafana
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/log/grafana
              name: grafana-log
            - mountPath: /var/lib/grafana
              name: grafana-lib
            - mountPath: /etc/grafana
              name: grafana-etc
      volumes:
        - name: grafana-lib
          emptyDir: {}
        - name: grafana-log
          emptyDir: {}
        - name: grafana-etc
          emptyDir: {}

